sudo: required

language: python3

services:
  - docker

before_install:
- docker build . -t pybat-lead-acid
- docker run -dt --name app pybat-lead-acid

script:
- docker exec app python -m unittest discover

after_script:
- docker rm -f app
