sudo: false

dist: xenial

language: python

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - gfortran
    - gcc
    - libopenblas-dev
    - liblapack-dev
    - graphviz

matrix:
    include:
        # Unit testing on all supported Python versions on Ubuntu
        # - python: "2.7"
        #   env:
        #     - PYBAMM_UNIT=true
        #   if: type != cron
        # - python: "2.7.6"
        #   env:
        #     - PYBAMM_UNIT=true
        #   if: type != cron
        # - python: "3.4"
        #   env:
        #     - PYBAMM_UNIT=true
        #   if: type != cron
        - python: "3.5"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.5-dev
          env:
            - PYBAMM_UNIT=true
            - PYBAMM_EXAMPLES=true
            - PYBAMM_SCIKITS_ODES=true
          if: type != cron
        - python: "3.6"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.6-dev
          env:
            - PYBAMM_UNIT=true
            - PYBAMM_EXAMPLES=true
            - PYBAMM_SCIKITS_ODES=true
        - python: "3.6"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.6-dev
          env:
            - PYBAMM_UNIT=true
            - PYBAMM_SCIKITS_ODES=true
          if: type != cron
        - python: "3.7"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.7-dev
          env:
            - PYBAMM_UNIT=true
            - PYBAMM_EXAMPLES=true
            - PYBAMM_SCIKITS_ODES=true
          if: type != cron
        # Unit testing on OS/X
        - os: osx
          python: 3.6
          env:
            - PYBAMM_UNIT=true
            - PYBAMM_EXAMPLES=true
          if: type != cron
        # Docs, style and cover checking, latest Python version only
        - python: "3.6"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.6-dev
          env:
            - PYBAMM_DOCS=true
          if: type != cron
        - python: "3.6"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.6-dev
          env:
            - PYBAMM_STYLE=true
          if: type != cron
        - python: "3.6"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.6-dev
          env:
            - PYBAMM_COVER=true
            - PYBAMM_SCIKITS_ODES=true
          if: type != cron
          # Cron jobs
        - python: "3.6"
          addons:
            apt:
              sources:
                - deadsnakes
              packages:
                - gfortran
                - gcc
                - libopenblas-dev
                - liblapack-dev
                - graphviz
                - python3.6-dev
          env:
            - PYBAMM_EXAMPLES=true
            - PYBAMM_SCIKITS_ODES=true
          if: type == cron

# Install graphviz for macs 
before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install graphviz; fi

# Install dependencies
# Note: Use pip (not apt-get) for Python dependencies
# Note: Only install normal dependencies for unit tests; these should be tested
#       without the packages from -dev and -doc!
install:
  - pip install pip==18
  - pip install .
  - if [[ $PYBAMM_DOCS == true ]]; then pip install -e .[docs]; fi;
  - if [[ $PYBAMM_STYLE == true || $PYBAMM_EXAMPLES ]]; then pip install -e .[dev]; fi;
  - if [[ $PYBAMM_COVER == true ]]; then pip install coverage codecov; fi;
  - if [[ $PYBAMM_SCIKITS_ODES == true ]]; then source scripts/install_scikits_odes.sh

before_script:
- python --version

# Note that default timeout is 10 minutes
# This can be changed with travis_wait, but that leads to
# issues with debug output:
# https://github.com/travis-ci/travis-ci/issues/5716
script:
  - if [[ $PYBAMM_UNIT == true ]]; then python run-tests.py --unit --folder all; fi;
  - if [[ $PYBAMM_DOCS == true ]]; then python run-tests.py --doctest; fi;
  - if [[ $PYBAMM_STYLE == true ]]; then python -m flake8; fi;
  - if [[ $PYBAMM_COVER == true ]]; then coverage run run-tests.py --nosub; fi;
  - if [[ $PYBAMM_EXAMPLES == true ]]; then travis_wait 120 python run-tests.py --examples; fi;

after_success:
  - if [[ $PYBAMM_COVER == true ]]; then codecov; fi;
