sudo: required

language: python

services:
  - docker

before_install:
- docker build . -t pybat-lead-acid
- docker run -dt --name app pybat-lead-acid

script:
- docker exec app python3 -m unittest discover

after_script:
- docker rm -f app

notifications:
  email:
    recipients:
      - sulzer@maths.ox.ac.uk
    on_success: change # default: change
    on_failure: always # default: always
