name: New Parameter Set
description: Add a third party parameter set to PyBaMM's documentation
body:
  - type: markdown
    attributes:
      value: |
      Third-party parameter sets can be added to PyBaMM by registering an entry
      point with `pybamm-parameter-sets` as described in our
      [documentation](https://pybamm.readthedocs.io/en/latest/source/parameters/parameter_sets.html).

      If you've created a parameter set and want to share it with the PyBamm Community,
      let us know, so we can add it to our list of
      [third-party parameter sets](https://pybamm.readthedocs.io/en/latest/source/parameters/parameter_sets.html#third-party-parameter-sets)
  - type: input
    attributes:
      id: parameter-set-url
      label: Where can we find your parameter set?
      description: Provide the Github URL or PyPi package name for your parameter set
      placeholder: https://github.com/AwesomeOrg/NewParameterSet
    validations:
      required: true
  - type: dropdown
    attributes:
      id: open-source-approved
      label: Is it licensed under an [Open Source Initiative Approved License](https://opensource.org/licenses)?
      options: ["Yes", "No"]
  - type: textarea
    attributes:
      id: feedback
      label: Any additional information?
      description: Thank you for making parameter set! Is there anything else we should know about it?

