on:
  push:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.7]
        include:
          - os: ubuntu-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.6
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
       python-version: ${{ matrix.python-version }}

    - name: Build manylinux Python wheels
      if: matrix.os == 'ubuntu-latest'
      uses: tlestang/python-wheels-manylinux-build@66bda7f
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
        commands: 'commands.sh'

    - name: Install standard python dependencies
      if: matrix.os != 'ubuntu-latest'
      run: |
        python -m pip install --upgrade pip wheel setuptools

    - name: Install build-time deps for MacOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install graphviz
        brew install openblas
        pip install wget
        git clone https://github.com/pybind/pybind11.git
        python scripts/setup_KLU_module_build.py

    - name: Build wheels for MacOS and Windows
      if: matrix.os != 'ubuntu-latest'
      run: |
        python -m pip wheel . -w dist/ --no-deps
        ls wheelhouse/

    - name: Publish wheels
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_TOKEN }}
