name: Check Docs links

on:
  push:
  pull_request:
  schedule:
    # Run everyday at 3 am UTC 
    - cron: 0 3 * * *

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        file-extension: '.rst, .md'
