name: Update version

on:
  workflow_dispatch:
  push:
    branches:
    - develop
  schedule:
    # Run at 10 am UTC on 28th every month
    - cron: 0 10 28 * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install wheel
        pip install --editable .

    - name: Get current date
      id: version
      run: echo "::set-output name=date::$(date +'v%y.%-m')"

    - name: Update version
      run: python scripts/update_version.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        branch-suffix: short-commit-hash
        commit-message: Update version to ${{ steps.date.outputs.version }}
        title: Update to ${{ steps.date.outputs.version }}
        body: |
            [x] Update to ${{ steps.date.outputs.version }}
            [ ] Check [release checklist](https://github.com/pybamm-team/PyBaMM/blob/develop/.github/release_checklist.md)
