name: Generate work precision sets

on:
  release:
   types: [created]
  workflow_dispatch: 
    
jobs:

  benchmarks_on_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Get current date
      run: echo "VERSION=$(date +'%y.%-m')" >> $GITHUB_ENV
    - name: Install PyBaMM
      run: python -m pip install pybamm==${{ env.VERSION }}
    - name: Run Solve time vs abstols
      run: |
        python benchmarks/work_precision_sets_abstols.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        branch-suffix: short-commit-hash
        commit-message: Work precision sets for PyBaMM version ${{ env.VERSION }}
        title: Work precision sets for PyBaMM version ${{ env.VERSION }}
        body: |
            Update work precision sets for PyBaMM version ${{ env.VERSION }} in `release_work_precision_sets.md`
